### ISSUE TITLE
Access AppVeyor via RDP for debugging

### ISSUE THREAD

**Issue by tyralla** [hydpy-dev/hydpy#102]
In case we ever need to access AppVeyor via RDP for debugging:

```yaml
environment:
  APPVEYOR_RDP_PASSWORD: ...

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

somewhere:
  - ps: $blockRdp = $true;
```
